apiVersion: apps/v1
kind: Deployment
metadata: 
  name: i27-eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: i27-eureka-dev
  template:
    metadata:
      labels:
        name: i27-eureka-dev
    spec:
      containers:
        - name: i27-eureka-dev
        # the below image should be dynamically change based on the devlelopment 
          image: DIT #docker.io/i27devopsb2/eureka:82b3701
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
# service 
apiVersion: v1
kind: Service
metadata:  
  name: i27-eureka-dev-svc
spec:
  selector:
    name: i27-eureka-dev
  ports:
  - protocol: TCP
    port: 80 # container or host or service
    targetPort: 8761 # ContainerPort 
  type: NodePort #ClusterIP, LoadBalancer, NodePort
  





